name: Diff PR Comment
description: Creates or updates PR comments with diff reports using shared logic

inputs:
  diff-type:
    description: "Type of diff (token, component)"
    required: true
  diff-generated:
    description: "Whether diff was generated (true/false/error)"
    required: true
  diff-content:
    description: "Generated diff content"
    required: true
  pr-number:
    description: "Pull request number"
    required: true
  github-token:
    description: "GitHub token for creating comments"
    required: true

runs:
  using: composite
  steps:
    - name: Find existing comment
      uses: peter-evans/find-comment@v3
      id: find-comment
      with:
        issue-number: ${{ inputs.pr-number }}
        comment-author: "github-actions[bot]"
        body-includes: "<!-- ${{ inputs.diff-type }}-diff-comment -->"
        token: ${{ inputs.github-token }}

    - name: Set comment details
      id: comment-details
      shell: bash
      run: |
        case "${{ inputs.diff-type }}" in
          "token")
            echo "emoji=🎨" >> $GITHUB_OUTPUT
            echo "title=Token Changes Report" >> $GITHUB_OUTPUT
            echo "description=token" >> $GITHUB_OUTPUT
            ;;
          "component")
            echo "emoji=🧩" >> $GITHUB_OUTPUT
            echo "title=Component Schema Changes Report" >> $GITHUB_OUTPUT
            echo "description=component schema" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "emoji=📊" >> $GITHUB_OUTPUT
            echo "title=Changes Report" >> $GITHUB_OUTPUT
            echo "description=diff" >> $GITHUB_OUTPUT
            ;;
        esac

    - name: Create or update PR comment (changes detected)
      uses: peter-evans/create-or-update-comment@v4
      if: inputs.diff-generated == 'true'
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        token: ${{ inputs.github-token }}
        body: |
          <!-- ${{ inputs.diff-type }}-diff-comment -->
          ## ${{ steps.comment-details.outputs.emoji }} ${{ steps.comment-details.outputs.title }}

          ${{ inputs.diff-content }}

          ---
          *This comment was automatically generated by the ${{ steps.comment-details.outputs.description }} diff tool. 🤖*
        edit-mode: replace

    - name: Create or update PR comment (no changes)
      uses: peter-evans/create-or-update-comment@v4
      if: inputs.diff-generated == 'false'
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        token: ${{ inputs.github-token }}
        body: |
          <!-- ${{ inputs.diff-type }}-diff-comment -->
          ## ${{ steps.comment-details.outputs.emoji }} ${{ steps.comment-details.outputs.title }}

          No ${{ steps.comment-details.outputs.description }} changes detected in this pull request.

          ---
          *This comment was automatically generated by the ${{ steps.comment-details.outputs.description }} diff tool. 🤖*
        edit-mode: replace

    - name: Create or update PR comment (error)
      uses: peter-evans/create-or-update-comment@v4
      if: inputs.diff-generated == 'error'
      with:
        comment-id: ${{ steps.find-comment.outputs.comment-id }}
        issue-number: ${{ inputs.pr-number }}
        token: ${{ inputs.github-token }}
        body: |
          <!-- ${{ inputs.diff-type }}-diff-comment -->
          ## ${{ steps.comment-details.outputs.emoji }} ${{ steps.comment-details.outputs.title }}

          ⚠️ **Error**: ${{ inputs.diff-content }}

          Please check the [workflow logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.

          ---
          *This comment was automatically generated by the ${{ steps.comment-details.outputs.description }} diff tool. 🤖*
        edit-mode: replace
