on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    name: An example job to comment a PR
    steps:
      - name: PR comment with file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: ../tools/diff-generator/src/lib/reports/report.txt
