name: Release

on:
  push:
    branches:
      - main
      - prerelease

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: 8.7.5
      - uses: moonrepo/setup-moon-action@v1
      - run: moon setup
      - run: moon run :build --query "projectSource~packages/*"
      - name: Publish
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: release"
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      # - name: Send a Slack notification if a publish happens
      # if: steps.changesets.outputs.published == 'true'
      # You can do something when a publish happens.
      # run: my-slack-bot send-notification --message "A new version of ${GITHUB_REPOSITORY} was published!"
