name: TDIFF - SPECTRUM FOUNDATIONS

on:
  workflow_dispatch:

jobs:
  tdiff:
    uses: ./.github/workflows/_tdiff.yml
    with:
      root: snapshot-s2-foundations # the spectrum-tokens data we want to compare against (branch of the repo)
    secrets: inherit
